
version: 2.1
orbs:
  slack: circleci/slack@4.4.0
commands:
  notify_slack:
    steps:
      - notify_slack_on_fail
      - notify_slack_on_success

  notify_slack_on_fail:
    description: "slack notification on job failure"
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_on_success:
    description: "slack notification on job success"
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

executors:
  compile:
    resource_class: small
    docker:
      - image: sbtscala/scala-sbt:openjdk-11.0.16_1.8.1_2.12.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  tests:
    executor: compile
    steps:
      - checkout
      - run: sbt test
      - notify_slack_on_fail
  deploy:
    filters:
      branches:
        only:
          - master
    executor: compile
    steps:
      - checkout
      - run: sbt publish
      - notify_slack_on_fail

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - tests:
          context:
            - silectis-read
            - silectis-notify
      - deploy:
          context:
            - silectis-publish
            - silectis-notify
          requires:
            - tests